# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3f69c7d161981597722239530a04d72"
application_url = "https://hera-recommendation.onrender.com"
embedded = true
name = "Hera Recommendation"

[access_scopes]
scopes = "read_all_orders,read_customers,read_inventory,read_locations,read_orders,read_products,write_products"
optional_scopes = []
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

[auth]
redirect_urls = ["https://hera-recommendation.onrender.com/auth/callback"]

[build]
automatically_update_urls_on_dev = false
